In [17]:
import tensorflow as tf

In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
## sentences
sent=[ 'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
## Define the vocabulary size
voc_size=10000

In [22]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8848, 7638, 2960, 3204],
 [8848, 7638, 2960, 6548],
 [8848, 5766, 2960, 1114],
 [5960, 7604, 4618, 2018, 6256],
 [5960, 7604, 4618, 2018, 5307],
 [9781, 8848, 4895, 2960, 5465],
 [3036, 4155, 1308, 2018]]

In [30]:
## word embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [31]:
import numpy as np

In [25]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8848 7638 2960 3204]
 [   0    0    0    0 8848 7638 2960 6548]
 [   0    0    0    0 8848 5766 2960 1114]
 [   0    0    0 5960 7604 4618 2018 6256]
 [   0    0    0 5960 7604 4618 2018 5307]
 [   0    0    0 9781 8848 4895 2960 5465]
 [   0    0    0    0 3036 4155 1308 2018]]


In [26]:
## feature representation
dim=10

In [32]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

f:\SimpleRNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [37]:
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

In [38]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step


array([[[-0.02441591, -0.00626072, -0.01941662,  0.03165538,
         -0.00615503, -0.0227066 ,  0.04215701,  0.02274587,
          0.02254638,  0.0446871 ],
        [-0.02441591, -0.00626072, -0.01941662,  0.03165538,
         -0.00615503, -0.0227066 ,  0.04215701,  0.02274587,
          0.02254638,  0.0446871 ],
        [-0.02441591, -0.00626072, -0.01941662,  0.03165538,
         -0.00615503, -0.0227066 ,  0.04215701,  0.02274587,
          0.02254638,  0.0446871 ],
        [-0.02441591, -0.00626072, -0.01941662,  0.03165538,
         -0.00615503, -0.0227066 ,  0.04215701,  0.02274587,
          0.02254638,  0.0446871 ],
        [-0.01794553, -0.03283625, -0.00548699,  0.00014548,
         -0.02180787, -0.02732451,  0.01751299, -0.00466578,
          0.03531945, -0.02685033],
        [-0.04531366,  0.0150112 ,  0.00765967,  0.00855082,
         -0.01108035,  0.03117298, -0.00187721,  0.03959831,
         -0.02676558, -0.01981737],
        [-0.01573058,  0.02924801, -0.00575775, -0.0